function results = Run_SIB1_SuccessRate_NoneVsSparse_Parfor(varargin)

% End-to-end SIB1 access simulation for the selected sensing-pilot policies.
rootDir = fileparts(mfilename('fullpath'));
addpath(rootDir);
addpath(fullfile(rootDir, 'NRCellSearchMIBAndSIB1RecoveryExample'));

rng(20260416);

[runMode, simOverrides] = SIB1_Setup.parseInputs(varargin{:});
sim = SIB1_Setup.buildSimConfig(runMode, simOverrides);
config = SIB1_Setup.buildWaveformConfig();

% Generate one normalized transmit waveform per pilot strategy.
[waveformsUnitPower, waveformMeta, sampleRate, activeDutyCycle] = ...
    SIB1_Setup.prepareWaveforms(config, sim.PilotStrategies);

rxConfig = SIB1_Setup.buildRxConfig(sampleRate, config, waveformMeta{1});
noiseInfo = SIB1_Setup.computeNoise(sim);
channelModel = SIB1_Channel.buildUMiLOSChannelModel(sim, sampleRate);
beamProfileRef = SIB1_Beam.buildSSBBeamSweepProfile( ...
    sim, config, waveformMeta{1}, mean(sim.UEAzimuthRange_deg));

if sim.UseParallelFine
    sim.UseParallelFine = SIB1_Setup.ensureParallelPool(sim.NumWorkers);
end

fineTxPower_dBm = -30:5:10;
fineStart_dBm = fineTxPower_dBm(1);
fineEnd_dBm = fineTxPower_dBm(end);

% The coarse result placeholder keeps the saved result schema stable.
coarseResults = struct( ...
    'Skipped', true, ...
    'Reason', 'Coarse sweep skipped; direct fine sweep over known range.', ...
    'TxPower_dBm', sim.CoarseTxPower_dBm(:), ...
    'NumMonteCarlo', sim.NumMonteCarloCoarse, ...
    'SuccessFlags', [], ...
    'BCHFlags', [], ...
    'DCIFlags', [], ...
    'SIB1Flags', [], ...
    'SuccessRate', [], ...
    'BCHSuccessRate', [], ...
    'DCISuccessRate', [], ...
    'SIB1SuccessRate', []);


% Run the focused Monte Carlo sweep.
fprintf('\nSkipping coarse sweep and running direct fine parfor sweep.\n');
fprintf('Known SIB1 access range: %.1f to %.1f dBm with %d trials per point.\n', ...
    fineStart_dBm, fineEnd_dBm, sim.NumMonteCarloFine);

fineResults = SIB1_MC.runMonteCarloBlock( ...
    sim, fineTxPower_dBm, sim.NumMonteCarloFine, waveformsUnitPower, ...
    waveformMeta, config, channelModel, noiseInfo.Power_W, rxConfig, 100000, ...
    sim.UseParallelFine);

results = SIB1_Report.buildResults( ...
    sim, config, sampleRate, activeDutyCycle, noiseInfo, channelModel, ...
    beamProfileRef, waveformMeta, coarseResults, fineResults);

% Persist data and figures for later inspection.
SIB1_Report.saveResults(rootDir, results);
SIB1_Report.plotSuccessRates(rootDir, fineTxPower_dBm, fineResults, sim.PilotStrategies);
SIB1_Report.printSummary( ...
    sim, channelModel, beamProfileRef, activeDutyCycle, noiseInfo.Power_dBm, ...
    fineStart_dBm, fineEnd_dBm);

end
