function printSummary( ...
    sim, channelModel, beamProfileRef, activeDutyCycle, noisePower_dBm, ...
    fineStart_dBm, fineEnd_dBm)

fprintf('\nWaveform generation and beam model:\n');
fprintf('  Base time-domain waveform is a single-stream SSB+SIB1 waveform from nrWaveformGenerator.\n');
fprintf('  Sparse sensing REs are inserted by modifying the BWP grid and remodulating the delta waveform.\n');
fprintf('  Total Tx power is the sum power of all %d antennas over the active interval.\n', ...
    sim.NumTransmitAntennas);
fprintf('  Beam sweeping is modeled as a time-varying gain seen by the user, not as a constant gain.\n');
fprintf('  UE azimuth is randomized uniformly over [%.2f, %.2f] deg at fixed %.1f m distance.\n', ...
    sim.UEAzimuthRange_deg(1), sim.UEAzimuthRange_deg(2), sim.Distance_m);
fprintf('  Reference user direction for saved beam profile: azimuth %.2f deg, elevation %.2f deg\n', ...
    beamProfileRef.UserAngle_deg(1), beamProfileRef.UserAngle_deg(2));
fprintf('  Strongest swept beam index: %d, gain %.2f dB\n', ...
    beamProfileRef.StrongestBeamIndex, beamProfileRef.MaxBeamGain_dB);
fprintf('  Beam sweep gain on active symbols ranges from %.2f to %.2f dB\n', ...
    beamProfileRef.MinBeamGain_dB, beamProfileRef.MaxBeamGain_dB);
fprintf('  Active-duty-cycle power definition: %.2f %% of waveform samples are active.\n', ...
    100 * activeDutyCycle);
fprintf('  3GPP %s LOS base path loss: %.2f dB\n', ...
    sim.PathLossScenario, channelModel.BasePathLoss_dB);
fprintf('  Additional realistic impairment: shadow fading std %.2f dB\n', ...
    channelModel.ShadowFadingStd_dB);
fprintf('  Integrated noise over %.2f MHz RF bandwidth: %.2f dBm\n', ...
    sim.RFFrontEndBandwidth_Hz / 1e6, noisePower_dBm);
fprintf('  Focused sweep range: %.1f to %.1f dBm, Monte Carlo = %d\n', ...
    fineStart_dBm, fineEnd_dBm, sim.NumMonteCarloFine);

end
